name: Workflow B - Project

on:
  workflow_call:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  project:
    runs-on: ubuntu-latest
    name: ADD TO PROJECT
    steps:
    - uses: srggrs/assign-one-project-github-action@1.3.1
      if: ${{ startsWith(github.event.issue.body, '# Security Request for Information (RFI)') }}
      with:
        project: 'https://github.com/users/RaydioAM/projects/6'
        column_name: 'test-col-1'
