name: Top-Level Action Caller

on:
  issues:
    types: [opened]

jobs:
  call-A:
    uses: ./.github/workflows/workflow-A.yml
  call-B:
    needs: call-A
    uses: ./.github/workflows/workflow-B.yml
    secrets:
      token: ${{ secrets.TEST_ALL_EVERYTHING }}
