name: Top-Level Action Caller

on:
  issues:
    types: [opened]

jobs:
  call-A:
#    uses: ./.github/workflows/workflow-B-test.yml
#    secrets: inherit
    uses: ./.github/workflows/workflow-A.yml
  call-B:
    needs: call-A
#    uses: ./.github/workflows/workflow-B.yml
    uses: ./.github/workflows/workflow-B-test.yml
    secrets: inherit
