name: Workflow B - Project

on:
  workflow_call:

env:
  GITHUB_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}

jobs:
  project:
    runs-on: ubuntu-latest
    name: ADD TO PROJECT
    steps:
    - uses: srggrs/assign-one-project-github-action@1.3.1
      if: |
        contains(github.event.issue.labels.*.name, 'activity-security-questionnaire')
      with:
        project: 'https://github.com/users/RaydioAM/projects/6'
        column_name: 'test-col-1'
